name: echo
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'
    - cron:  '5 7 * * *'
    - cron:  '10 7 * * *'
    - cron:  '15 7 * * *'
    - cron:  '20 7 * * *'
    - cron:  '25 7 * * *'
    - cron:  '30 7 * * *'
jobs:
  check-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: esp
        run: |          
          echo schedule ${{github.event.schedule}}
