name: twitter
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * *'
    - cron:  '5 5 * * *'
    - cron:  '10 5 * * *'
    - cron:  '15 5 * * *'
    - cron:  '20 5 * * *'
    - cron:  '25 5 * * *'
    - cron:  '30 5 * * *'
  workflow_dispatch:
    inputs:
      year:
        description: 'Year'     
        required: true
        default: '2021'
      month:
        description: 'Month'
        required: true
      day:
        description: 'Day'
        required: true
      lang:
        description: 'Lang'
        required: true
        default: 'es'
jobs:
  check-groovy:
    runs-on: ubuntu-latest
    env:
      GROOVY_VERSION: 3.0.5
      CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
      CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
      ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
      ACCESSTOKENSECRET: ${{ secrets.ACCESSTOKENSECRET }}
    steps:
      - uses: actions/checkout@v2
      - id: install
        shell: bash
        run: |          
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy $GROOVY_VERSION          

      - name: manual
        if: github.event.inputs.lang
          LANG=${{ github.event.inputs.lang }} groovy \
            -Dtwitter4j.oauth.consumerKey=${CONSUMERKEY} \
            -Dtwitter4j.oauth.consumerSecret=${CONSUMERSECRET} \
            -Dtwitter4j.oauth.accessToken=${ACCESSTOKEN} \
            -Dtwitter4j.oauth.accessTokenSecret=${ACCESSTOKENSECRET} \
            scripts/twitter.groovy ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} ${LANG}

      - name: esp
        if: github.event.schedule=='0 5 * * *'
          LANG=esp groovy \
            -Dtwitter4j.oauth.consumerKey=${CONSUMERKEY} \
            -Dtwitter4j.oauth.consumerSecret=${CONSUMERSECRET} \
            -Dtwitter4j.oauth.accessToken=${ACCESSTOKEN} \
            -Dtwitter4j.oauth.accessTokenSecret=${ACCESSTOKENSECRET} \
            scripts/twitter.groovy ${{ github.event.inputs.year }} ${{ github.event.inputs.month }} ${{ github.event.inputs.day }} ${LANG}

